In [4]:
import numpy as np

In [39]:
#generate random parameter matrix

np.random.seed(42)
def generateFun(n1,n2):
    temp = np.random.rand(n1,n2)
    return temp/temp.sum(axis=1)[:,None]
A = generateFun(3,3)
B = generateFun(3,2)
pi = generateFun(1,3).T
print(A)
print(B)
print(pi)

[[0.18205878 0.46212909 0.35581214]
 [0.65738127 0.17132261 0.17129612]
 [0.03807826 0.56784481 0.39407693]]
[[0.97175009 0.02824991]
 [0.5381355  0.4618645 ]
 [0.53870741 0.46129259]]
[[0.18115758]
 [0.3005149 ]
 [0.51832752]]


In [44]:
pi = np.array([0.2,0.4,0.4])
pi.shape=(-1,1)
print(pi.shape)

(4, 1)


In [63]:
# implement forward function and check it with data

O = [0,1,0]
A = np.array([[0.5,0.2,0.3],[0.3,0.5,0.2],[0.2,0.3,0.5]])
B = np.array([[0.5,0.5],[0.4,0.6],[0.7,0.3]])
pi = np.array([0.2,0.4,0.4])
pi.shape=(-1,1)
def forward(A,B,pi,O):
    # init the vector
    temp = pi * B[:,0][:,None]
    print(temp)
    
    for i in range(1,len(O)):
        b = B[:,O[i]][:,None]
        temp = np.matmul(A.T,temp)*b
        #print(temp)
    return temp.sum()
print(forward(A,B,pi,O))
#t = np.matmul(A,pi)       
#print(t*pi)
#print(B)
#t = B[:,1][:,None]
#print(type(t))
#print(t.shape)
#print(t)

[[0.1 ]
 [0.16]
 [0.28]]
0.130218


In [30]:
def backward(A, B, pi, O)

array([[0.73271833],
       [1.00067893],
       [1.40095913]])

In [28]:
t = A.sum(axis=1)
print(t.T)
print(type(t))
print(t.shape)

b = A/t.T
print(b)
b.sum(axis=0)

[0.73271833 1.00067893 1.40095913]
<class 'numpy.ndarray'>
(3,)
[[0.72866861 0.01238654 0.13306207]
 [0.71081055 0.03279583 0.31909347]
 [0.78386441 0.51336847 0.22334007]]


array([2.22334357, 0.55855085, 0.67549561])